export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_TOTALROWS = "FETCH_TOTALROWS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const GET_FILTERS = "GET_FILTERS";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_TYPECATEGORY = "CHANGE_TYPECATEGORY";
export const LOADING = "LOADING";
